/* Isolated marketing demos. No messages, settings or payments leave this preview. */
(() => {
'use strict';
const press = (buttons, selected) => buttons.forEach(b => b.setAttribute('aria-pressed',String(b===selected)));
const chat=document.querySelector('.fx-live-widget');
if(chat){
 const thread=chat.querySelector('.fx-live-messages'), form=chat.querySelector('form'), input=form.querySelector('input');let replyTimer;
 const initial=thread.innerHTML;
 function message(text,side){const p=document.createElement('p');p.className=side;p.textContent=text;thread.append(p);thread.scrollTop=thread.scrollHeight;}
 function send(question,answer){clearTimeout(replyTimer);thread.querySelector('[data-typing]')?.remove();message(question,'fx-sent');const typing=document.createElement('p');typing.className='fx-received';typing.dataset.typing='true';typing.textContent='Alex is typing…';thread.append(typing);thread.scrollTop=thread.scrollHeight;replyTimer=setTimeout(()=>{typing.remove();message(answer,'fx-received')},650);}
 const answers={delivery:['How long does delivery take?','Standard delivery takes 3–5 business days. Tell me where it’s going and I’ll help you check the best option.'],person:['Could I speak to your team?','You’re speaking with Alex. I’m here to help — what would you like to know?']};
 chat.querySelectorAll('[data-live-question]').forEach(b=>b.addEventListener('click',()=>send(...answers[b.dataset.liveQuestion])));
 form.addEventListener('submit',e=>{e.preventDefault();const q=input.value.trim();if(!q)return;input.value='';const lower=q.toLowerCase();const answer=/deliver|ship|arriv/.test(lower)?answers.delivery[1]:/lamp|light|dim/.test(lower)?'The reading lamp has adjustable brightness. Would you like help choosing a finish?':/return|refund/.test(lower)?'Unused items can be returned within 30 days in this example. I can help you with the next step.':'Thanks for trying the chat! In your Mill widget, this message reaches your team so they can help personally.';send(q,answer);});
 chat.querySelector('[data-chat-reset]').addEventListener('click',()=>{clearTimeout(replyTimer);thread.innerHTML=initial;input.value='';});
}
const tools=[...document.querySelectorAll('[data-live-tool]')];
const toolScenes={messages:['PERSONAL REPLIES','<p class="fx-tool-question">I’m choosing a lamp for a small desk.</p><p class="fx-tool-answer">I’d suggest the reading lamp. It has a smaller base, and you can adjust the brightness.</p><small>Alex · Customer care <span>✓ Delivered</span></small>'],files:['A LITTLE MORE CLARITY','<div class="fx-file-example"><b>▧</b><div><strong>My workspace.jpg</strong><small>Image shared in the conversation</small></div></div><p class="fx-tool-answer">That helps. The smaller base should fit comfortably beside your monitor.</p><small>Alex · Customer care <span>✓ Full picture received</span></small>'],rating:['A GOOD LAST IMPRESSION','<div class="fx-rating-example"><strong>How was your conversation?</strong><span>★★★★★</span><p>Thanks, Alex. That was exactly what I needed.</p></div><small>Conversation resolved <span>Transcript available</span></small>']};
tools.forEach(b=>b.addEventListener('click',()=>{press(tools,b);const s=toolScenes[b.dataset.liveTool];document.querySelector('[data-live-tool-label]').textContent=s[0];document.querySelector('[data-live-tool-content]').innerHTML=s[1]}));
const availability=[...document.querySelectorAll('[data-availability]')];availability.forEach(b=>b.addEventListener('click',()=>{press(availability,b);const away=b.dataset.availability==='away';document.querySelector('.fx-availability-card').dataset.away=String(away);document.querySelector('[data-availability-title]').textContent=away?'Leave a little hello.':'We’re here. Let’s talk.';document.querySelector('[data-availability-copy]').textContent=away?'The team is away. Leave your message and email, and we’ll get back to you when we’re online.':'Your team is online and ready to help with the next question.';document.querySelector('[data-availability-status]').textContent=away?'Leave a message →':'Chat with the team →'}));
const queue=[...document.querySelectorAll('[data-inbox-person]')];
if(queue.length){const people={emma:['Emma Wilson','EW','Hi! Could you check whether my order can arrive before Friday?','Hi Emma! Let me check the delivery options for your order.','Delivery & returns'],james:['James Brooks','JB','I’ve just placed an order. Can I change the delivery address?','Hi James. I’ll check the order status before we update the address.','Your orders'],sophie:['Sophie Lee','SL','Could you help me choose a desk for a small room?','Absolutely, Sophie. Tell me the space you have and we’ll find a good fit.','Desks & workspace']};
 const reset=()=>{document.querySelector('.fx-inbox-note').hidden=true;document.querySelector('.fx-inbox-event').hidden=true;document.querySelector('[data-inbox-owner]').textContent='Assigned to Alex';document.querySelector('[data-inbox-owner-name]').textContent='Alex';document.querySelector('[data-inbox-action=note]').textContent='▣ Add a private note';document.querySelector('[data-inbox-action=assign]').textContent='Assign to Sam →';document.querySelector('[data-inbox-action=assign]').dataset.assigned='false';};
 queue.forEach(b=>b.addEventListener('click',()=>{press(queue,b);reset();const p=people[b.dataset.inboxPerson];['[data-inbox-name]','[data-inbox-profile]'].forEach(s=>document.querySelector(s).textContent=p[0]);document.querySelector('[data-inbox-initials]').textContent=p[1];document.querySelector('[data-inbox-question]').textContent=p[2];document.querySelector('[data-inbox-answer]').textContent=p[3];document.querySelector('[data-inbox-page]').textContent=p[4];document.querySelector('.fx-inbox-note p').textContent='@Sam — could you help with '+p[0].split(' ')[0]+'’s question? The conversation and customer details are here.';}));
 document.querySelector('[data-inbox-action=note]').addEventListener('click',e=>{const note=document.querySelector('.fx-inbox-note');note.hidden=!note.hidden;e.currentTarget.textContent=note.hidden?'▣ Add a private note':'✓ Private note added';});
 document.querySelector('[data-inbox-action=assign]').addEventListener('click',e=>{const assigned=e.currentTarget.dataset.assigned==='true';e.currentTarget.dataset.assigned=String(!assigned);document.querySelector('[data-inbox-owner]').textContent=assigned?'Assigned to Alex':'Assigned to Sam';document.querySelector('[data-inbox-owner-name]').textContent=assigned?'Alex':'Sam';document.querySelector('.fx-inbox-event').hidden=assigned;e.currentTarget.textContent=assigned?'Assign to Sam →':'Return to Alex →';});
}
const designer=document.querySelector('.fx-designer');
if(designer){const stage=designer.querySelector('.fx-website-stage');const colours=[...designer.querySelectorAll('[data-brand-colour]')],shapes=[...designer.querySelectorAll('[data-launcher]')],devices=[...designer.querySelectorAll('[data-device]')];colours.forEach(b=>b.addEventListener('click',()=>{press(colours,b);stage.style.setProperty('--widget-colour',b.dataset.brandColour)}));shapes.forEach(b=>b.addEventListener('click',()=>{press(shapes,b);stage.dataset.shape=b.dataset.launcher}));devices.forEach(b=>b.addEventListener('click',()=>{press(devices,b);stage.dataset.device=b.dataset.device}));designer.querySelector('#fx-brand-name').addEventListener('input',e=>designer.querySelectorAll('[data-brand-name]').forEach(n=>n.textContent=e.target.value.trim()||'Your brand'));const launcher=designer.querySelector('.fx-launcher'),preview=designer.querySelector('.fx-brand-chat');const open=state=>{preview.hidden=!state;launcher.setAttribute('aria-expanded',String(state));};launcher.addEventListener('click',()=>open(preview.hidden));designer.querySelector('[data-widget-close]').addEventListener('click',()=>open(false));}
const siteButtons=[...document.querySelectorAll('[data-site]')];
const sites={willow:['Willow Atelier','A question about delivery','AL','Alex','A little help finding the right thing?','#315f51','Sage','Monday–Friday · 9am–6pm','Store support','Products, delivery & returns'],northline:['Northline Studio','A new project enquiry','SM','Sam','Tell us a little about your next project.','#a76850','Terracotta','Monday–Thursday · 10am–5pm','Studio team','Services, projects & consultations'],harbour:['Harbour Software','Help getting started','JR','Jordan','Need a hand finding your next step?','#2a5ea1','Harbour blue','Monday–Friday · 8am–8pm','Customer success','Product guides & account help']};
siteButtons.forEach(b=>b.addEventListener('click',()=>{press(siteButtons,b);const s=sites[b.dataset.site];document.querySelector('[data-site-conversation]').textContent=s[0]+' · '+s[1];document.querySelector('[data-site-initials]').textContent=s[2];document.querySelector('[data-site-owner]').textContent='Assigned to '+s[3];document.querySelector('[data-site-setting-name]').textContent=s[0];document.querySelector('[data-site-greeting]').textContent=s[4];document.querySelector('[data-site-colour]').style.background=s[5];document.querySelector('[data-site-tone]').textContent=s[6];document.querySelector('[data-site-hours]').textContent=s[7];document.querySelector('[data-site-team]').textContent=s[8];document.querySelector('[data-site-knowledge]').textContent=s[9]}));
const contexts=[...document.querySelectorAll('[data-context]')];
const contextScenes={conversation:['THE WHOLE CONVERSATION',[['Today · 10:42 AM','A question about delivery','“Could it arrive before Friday?”'],['Yesterday · 3:18 PM','Help choosing a reading lamp','Alex shared the product details. Conversation resolved.']],'Alex has the conversation history, ready to pick up where you left off.'],browsing:['THE PAGE BEHIND THE QUESTION',[['Currently viewing','Delivery & returns','Emma opened the chat on your delivery page.'],['Earlier in this visit','The reading lamp','Product details → oak finish → delivery information.']],'Alex can see what Emma was looking at before asking for help.'],orders:['CONNECTED STORE CONTEXT',[['Recent order · Willow Atelier','The reading lamp · Oak','Order confirmed · Preparing for dispatch.'],['Customer relationship','A familiar face','Previous order and conversation details are close at hand.']],'Alex has the connected order details beside the conversation.']};
contexts.forEach(b=>b.addEventListener('click',()=>{press(contexts,b);const s=contextScenes[b.dataset.context];document.querySelector('[data-context-label]').textContent=s[0];const timeline=document.querySelector('[data-context-timeline]');timeline.replaceChildren();s[1].forEach(item=>{const a=document.createElement('article');a.append(document.createElement('i'));['small','strong','p'].forEach((tag,i)=>{const el=document.createElement(tag);el.textContent=item[i];a.append(el)});timeline.append(a)});document.querySelector('[data-context-note]').textContent=s[2]}));
})();
