BEGIN;
SELECT set_config('request.jwt.claim.role','service_role',true);
SELECT set_config('request.jwt.claims','{"role":"service_role"}',true);
DO $$
DECLARE w uuid; w2 uuid; vs uuid; c1 uuid; c2 uuid; r uuid:=gen_random_uuid(); r2 uuid:=gen_random_uuid(); failed boolean; balance jsonb;
BEGIN
 INSERT INTO public.workspaces(name,slug,widget_public_key) VALUES('AI quota regression','ai-quota-'||substr(gen_random_uuid()::text,1,8),'wk_'||replace(gen_random_uuid()::text,'-','')) RETURNING id INTO w;
 UPDATE public.workspace_admin_controls SET access_mode='standard',plan_id='essential',limits='{"monthly_ai_requests":1}' WHERE workspace_id=w;
 INSERT INTO public.visitor_sessions(workspace_id,session_token_hash,expires_at) VALUES(w,gen_random_uuid()::text,now()+interval '1 day') RETURNING id INTO vs;
 INSERT INTO public.conversations(workspace_id,visitor_session_id) VALUES(w,vs) RETURNING id INTO c1;
 UPDATE public.conversations SET status='closed' WHERE id=c1;
 INSERT INTO public.conversations(workspace_id,visitor_session_id) VALUES(w,vs) RETURNING id INTO c2;
 PERFORM public.reserve_ai_conversation_credit(w,c1,r);
 failed:=false;
 BEGIN PERFORM public.reserve_ai_conversation_credit(w,c2,r2); EXCEPTION WHEN raise_exception THEN IF SQLERRM LIKE 'AI_QUOTA_EXHAUSTED:%' THEN failed:=true; ELSE RAISE; END IF; END;
 IF NOT failed THEN RAISE EXCEPTION 'Reserved last credit allowed overspend'; END IF;
 PERFORM public.finish_ai_conversation_credit(w,r,false);
 IF (public.workspace_ai_credit_balance(w)->>'used')::int<>0 THEN RAISE EXCEPTION 'Failure consumed credit'; END IF;
 PERFORM public.reserve_ai_conversation_credit(w,c2,r2);
 PERFORM public.finish_ai_conversation_credit(w,r2,true);
 PERFORM public.reserve_ai_conversation_credit(w,c2,gen_random_uuid());
 balance:=public.workspace_ai_credit_balance(w);
 IF balance->>'used'<>'1' OR balance->>'remaining'<>'0' THEN RAISE EXCEPTION 'Repeat conversation counted twice'; END IF;
 UPDATE public.workspace_admin_controls SET plan_id='growth',limits='{}' WHERE workspace_id=w;
 IF public.workspace_ai_credit_balance(w)->>'remaining'<>'499' THEN RAISE EXCEPTION 'Upgrade did not preserve used credits'; END IF;
 UPDATE public.workspace_admin_controls SET limits='{"monthly_ai_requests":2}' WHERE workspace_id=w;
 PERFORM public.reserve_ai_conversation_credit(w,c1,r);
 failed:=false;
 BEGIN PERFORM public.reserve_ai_conversation_credit(w,c1,gen_random_uuid()); EXCEPTION WHEN raise_exception THEN IF SQLERRM LIKE 'AI_BUSY:%' THEN failed:=true; ELSE RAISE; END IF; END;
 IF NOT failed THEN RAISE EXCEPTION 'Concurrent same conversation not serialized'; END IF;
 UPDATE public.ai_conversation_credits SET updated_at=now()-interval '3 minutes' WHERE workspace_id=w AND request_id=r;
 PERFORM public.reserve_ai_conversation_credit(w,c1,r2);
 PERFORM public.finish_ai_conversation_credit(w,r,false);
 IF NOT EXISTS(SELECT 1 FROM public.ai_conversation_credits WHERE workspace_id=w AND conversation_id=c1 AND status='reserved') THEN RAISE EXCEPTION 'Old request released new reservation'; END IF;
 PERFORM public.finish_ai_conversation_credit(w,r2,false);
 INSERT INTO public.ai_conversation_credits(workspace_id,period_start,conversation_id,request_id,status) VALUES(w,now()-interval '2 months',c1,gen_random_uuid(),'success');
 IF public.workspace_ai_credit_balance(w)->>'used'<>'1' THEN RAISE EXCEPTION 'Previous month usage carried forward'; END IF;
 UPDATE public.workspace_admin_controls SET plan_id='starter' WHERE workspace_id=w;
 IF app_private.plan_hide_branding(w) THEN RAISE EXCEPTION 'Starter granted white label'; END IF;
 PERFORM app_private.ensure_widget_config(w);
 UPDATE public.widget_configs SET draft_json=jsonb_set(draft_json,'{showPoweredBy}','false'),published_json=jsonb_set(published_json,'{showPoweredBy}','false') WHERE workspace_id=w;
 IF EXISTS(SELECT 1 FROM public.widget_configs WHERE workspace_id=w AND (draft_json->>'showPoweredBy'<>'true' OR published_json->>'showPoweredBy'<>'true')) THEN RAISE EXCEPTION 'Direct write bypassed branding'; END IF;
 INSERT INTO public.allowed_domains(workspace_id,domain,verified) VALUES(w,'credits.example.com',true);
 INSERT INTO public.widget_site_configs(workspace_id,domain,draft_json,published_json,published_version)
 SELECT w,'credits.example.com',jsonb_set(draft_json,'{showPoweredBy}','false'),jsonb_set(published_json,'{showPoweredBy}','false'),published_version FROM public.widget_configs WHERE workspace_id=w;
 IF EXISTS(SELECT 1 FROM public.widget_site_configs WHERE workspace_id=w AND published_json->>'showPoweredBy'<>'true') THEN RAISE EXCEPTION 'Site config bypassed branding'; END IF;
 UPDATE public.workspace_admin_controls SET features='{"hide_powered_by":true}' WHERE workspace_id=w;
 IF NOT app_private.plan_hide_branding(w) THEN RAISE EXCEPTION 'Active admin override ignored'; END IF;
 UPDATE public.workspace_admin_controls SET override_expires_at=now()-interval '1 second' WHERE workspace_id=w;
 IF app_private.plan_hide_branding(w) THEN RAISE EXCEPTION 'Expired override granted branding'; END IF;
 failed:=false;
 BEGIN PERFORM public.reserve_ai_conversation_credit(gen_random_uuid(),c1,gen_random_uuid()); EXCEPTION WHEN raise_exception THEN failed:=true; END;
 IF NOT failed THEN RAISE EXCEPTION 'Cross-tenant credit allowed'; END IF;
 IF has_function_privilege('authenticated','public.reserve_ai_conversation_credit(uuid,uuid,uuid)','EXECUTE') THEN RAISE EXCEPTION 'Customers can directly reserve credits'; END IF;
END $$;
ROLLBACK;
