BEGIN;
DO $$ DECLARE w uuid; u uuid; r jsonb; original jsonb; sess jsonb; visitor public.visitor_sessions; cfg public.workspace_chat_settings; failed boolean:=false;
BEGIN
 SELECT id INTO u FROM auth.users LIMIT 1;
 INSERT INTO public.workspaces(name,slug,widget_public_key) VALUES('Site isolation regression','sites-test-'||substr(gen_random_uuid()::text,1,8),'wk_'||replace(gen_random_uuid()::text,'-','')) RETURNING id INTO w;
 INSERT INTO public.workspace_members(workspace_id,user_id,role) VALUES(w,u,'owner');
 INSERT INTO public.allowed_domains(workspace_id,domain,verified) VALUES(w,'first.example.com',true),(w,'second.example.com',true);
 PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);
 r:=public.site_widget_studio(w,'first.example.com'); original:=r->'published';
 UPDATE public.widget_configs SET published_version=7 WHERE workspace_id=w;
 r:=public.site_widget_studio(w,'first.example.com','save',(r->'draft')||'{"primaryColor":"#AABBCC"}'::jsonb);
 IF r->'published'->>'primaryColor'<>original->>'primaryColor' THEN RAISE EXCEPTION 'Draft leaked'; END IF;
 r:=public.site_widget_studio(w,'first.example.com','publish',NULL,7);
 IF r->'published'->>'primaryColor'<>'#AABBCC' THEN RAISE EXCEPTION 'Publish failed'; END IF;
 r:=public.site_widget_studio(w,'www.first.example.com');
 IF r->'published'->>'primaryColor'<>'#AABBCC' THEN RAISE EXCEPTION 'www scope differs'; END IF;
 r:=public.site_widget_studio(w,'second.example.com');
 IF r->'published'->>'primaryColor'<>original->>'primaryColor' THEN RAISE EXCEPTION 'Other site modified'; END IF;
 BEGIN PERFORM public.site_widget_studio(w,'first.example.com','publish',NULL,7); EXCEPTION WHEN raise_exception THEN IF SQLERRM='PUBLISH_CONFLICT' THEN failed:=true; ELSE RAISE; END IF; END;
 IF NOT failed THEN RAISE EXCEPTION 'Publish CAS failed'; END IF;
 r:=public.site_widget_studio(w,'first.example.com','save',(r->'draft')||'{"launcherIcon":"custom","launcherIconAssetId":null}'::jsonb);
 IF r->'draft'->>'launcherIcon'='custom' THEN RAISE EXCEPTION 'Customer gained custom launcher'; END IF;
 failed:=false;
 BEGIN PERFORM public.site_widget_studio(w,'unlisted.example.com','save',r->'draft'); EXCEPTION WHEN raise_exception THEN failed:=true; END;
 IF NOT failed THEN RAISE EXCEPTION 'Unlisted site accepted'; END IF;
 INSERT INTO public.site_chat_settings(workspace_id,domain,config,version) VALUES(w,'first.example.com','{"enabled":true,"ratingEnabled":true}',1);
 sess:=public.widget_create_or_resume_visitor_session(p_workspace_id=>w,p_locale=>'en');
 PERFORM public.bind_widget_session_site(w,sess->>'session_token','https://www.first.example.com');
 visitor:=app_private.resolve_visitor_session(w,sess->>'session_token');
 cfg:=app_private.session_chat_settings(w,visitor);
 IF cfg.config->>'enabled'<>'true' OR visitor.site_domain<>'first.example.com' THEN RAISE EXCEPTION 'Session site rules incorrect'; END IF;
 failed:=false;
 BEGIN PERFORM app_private.require_pre_chat_submission(w,visitor); EXCEPTION WHEN raise_exception THEN failed:=true; END;
 IF NOT failed THEN RAISE EXCEPTION 'Site pre-chat not enforced'; END IF;
 failed:=false;
 BEGIN PERFORM public.bind_widget_session_site(w,sess->>'session_token','https://second.example.com'); EXCEPTION WHEN raise_exception THEN failed:=true; END;
 IF NOT failed THEN RAISE EXCEPTION 'Cross-site session accepted'; END IF;
 UPDATE public.workspace_members SET role='viewer' WHERE workspace_id=w AND user_id=u;
 failed:=false;
 BEGIN PERFORM public.site_widget_studio(w,'first.example.com','publish'); EXCEPTION WHEN raise_exception THEN failed:=true; END;
 IF NOT failed THEN RAISE EXCEPTION 'Viewer may publish'; END IF;
END $$;
ROLLBACK;
