#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DB_NAME="${SITE_CHAT_TEST_DB:-site_chat_test}"
OUTPUT="${SITE_CHAT_TYPES_OUTPUT:-${ROOT_DIR}/packages/shared/src/database.types.ts}"
POSTGRES_META_SERVER="${ROOT_DIR}/node_modules/@supabase/postgres-meta/dist/server/server.js"

ensure_database() {
  if ! sudo -u postgres psql -d "${DB_NAME}" -c '\q' >/dev/null 2>&1; then
    "${ROOT_DIR}/scripts/run-db-tests.sh" >/dev/null
  fi
}

if command -v supabase >/dev/null 2>&1 && supabase status >/dev/null 2>&1; then
  supabase gen types typescript --local > "${OUTPUT}"
  exit 0
fi

ensure_database

PG_META_GENERATE_TYPES=typescript \
PG_META_DB_HOST=127.0.0.1 \
PG_META_DB_PORT=5432 \
PG_META_DB_NAME="${DB_NAME}" \
PG_META_DB_USER=postgres \
PG_META_DB_PASSWORD=postgres \
PG_META_GENERATE_TYPES_INCLUDED_SCHEMAS=public \
node "${POSTGRES_META_SERVER}" > "${OUTPUT}.tmp"
{
  echo "// Generated by scripts/gen-database-types.sh — do not edit manually."
  cat "${OUTPUT}.tmp"
} > "${OUTPUT}"
rm "${OUTPUT}.tmp"
